# Generated by Django 5.2.7 on 2025-12-21 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]+$', 'Formato inválido para RUC/Cédula.')], verbose_name='RUC/Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números.')]),
        ),
    ]
