# Generated by Django 5.2.7 on 2025-11-22 21:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_direccion_ciudad_alter_direccion_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nombre_completo',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras y espacios.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Nombre de usuario inválido.')]),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
