# Generated by Django 5.2.7 on 2025-11-22 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_direccion_ciudad_alter_direccion_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('producto_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_base', to='api.producto')),
                ('producto_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_sugeridas', to='api.producto')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('producto_base', 'producto_recomendado')},
            },
        ),
    ]
