# Generated by Django 5.2.7 on 2025-11-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_historicalpedido_vendedor_pedido_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVOLUCION', 'Devolución')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVOLUCION', 'Devolución')], default='PENDIENTE', max_length=15),
        ),
    ]
