# Generated by Django 5.2.7 on 2025-11-23 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usuario_sucursal_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente')], default='CLIENTE', help_text='Rol del usuario en el sistema', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Nombre de usuario inválido.')]),
        ),
    ]
