# Generated by Django 5.2.7 on 2025-11-23 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usuario_rol_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='metodo_pago',
            field=models.CharField(default='PAYPAL', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID de PayPal o Referencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='PAYPAL', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID de PayPal o Referencia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente')], default='CLIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Nombre inválido.')]),
        ),
    ]
