# Generated by Django 5.2.7 on 2025-11-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_historicalpedido_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
