# Generated by Django 5.2.7 on 2025-12-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_historicalpedido_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='tasa_mora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Mora %'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tasa_mora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Mora %'),
        ),
    ]
